const HOUSES = [
  {
    id: 1,
    key: 'fire',
    name: { ar: 'المنجم الخشبي', en: 'Wooden Mine' },
    img: 'asesst/house-fire.png',
    unlocked: true,
    coinMultiplier: 0.20,
    perkDesc: { ar: 'زيادة 20% على أرباح جمع العملات', en: '20% bonus on collected coins' },
  },
  {
    id: 2,
    key: 'light',
    name: { ar: 'منجم النحاس', en: 'Copper Mine' },
    img: 'asesst/house-light.png',
    unlock: { type: 'referrals', need: 3 },
    coinMultiplier: 0.35,
    perkDesc: { ar: 'زيادة 35% على أرباح جمع العملات', en: '35% bonus on collected coins' },
  },
  {
    id: 3,
    key: 'ice',
    name: { ar: 'منجم الجليد', en: 'Ice Mine' },
    img: 'asesst/house-ice.png',
    unlock: { type: 'referrals', need: 15 },
    coinMultiplier: 0.50,
    perkDesc: { ar: 'زيادة 50% على أرباح جمع العملات', en: '50% bonus on collected coins' },
  },
  {
    id: 4,
    key: 'nature',
    name: { ar: 'منجم الطبيعة', en: 'Nature Mine' },
    img: 'asesst/house-nature.png',
    unlock: { type: 'referrals', need: 45 },
    production: 0.0001,
    perkDesc: { ar: 'إنتاج 0.0001 دولار كل دقيقتين', en: 'Produces $0.0001 every two minutes' },
  },
  {
    id: 5,
    key: 'dark',
    name: { ar: 'منجم الظلام', en: 'Dark Mine' },
    img: 'asesst/house-dark.png',
    unlock: { type: 'ads', need: 50 },
    production: 0.0002,
    perkDesc: { ar: 'إنتاج 0.0002 دولار كل دقيقتين', en: 'Produces $0.0002 every two minutes' },
  },
  {
    id: 6,
    key: 'desert',
    name: { ar: 'منجم الصحراء', en: 'Desert Mine' },
    img: 'asesst/house-desert.png',
    unlock: { type: 'ads', need: 200 },
    coinMultiplier: 0,
    production: 0.0002,
    productionIntervalMs: 60000,
    perkDesc: { ar: 'تنتج 0.0002 USDT تلقائيًا كل دقيقة بعد إكمال 200 إعلان', en: 'Produces 0.0002 USDT every minute after completing 200 ads' },
  },
];

function hName(house) { return house.name[LANG]; }
function hPerkDesc(house) { return house.perkDesc[LANG]; }
